site_name: Métodos de Procesamiento y Análisis de Big Data

nav:
  - Inicio: index.md
  
  - Introducción:
    - Fundamentos de Big Data: tema11.md
    - Introducción al ecosistema Spark: tema12.md
    - RDD, DataFrame y Dataset: tema13.md
    - Instalación y configuración de Spark: tema14.md
    - Primeros pasos con PySpark: tema15.md

  - PySpark y SparkSQL:
    - Fundamentos de DataFrames en Spark: tema21.md
    - Manipulación y Transformación de Datos: tema22.md
    - Consultas y SQL en Spark: tema23.md
    - Optimización y Rendimiento: tema24.md

  - Arquitectura y Diseño de Flujos ETL:
    - Diseño y Orquestación de Pipelines ETL: tema31.md
    - Conexión a Múltiples Fuentes de Datos: tema32.md
    - Procesamiento Escalable y Particionamiento: tema33.md
    - Manejo de Esquemas y Calidad de Datos: tema34.md
    - Monitorización y Troubleshooting de Pipelines: tema35.md
    - Seguridad en ETL y Protección de Datos: tema36.md
    - Patrones de Diseño y Optimización en la Nube: tema37.md

  - Automatización y Orquestación con Apache Airflow:
    - Arquitectura y componentes de Airflow: tema41.md
    - DAGs, operadores y tareas: tema42.md
    - Integración con ecosistema Big Data: tema43.md
    - Monitoreo, logging y manejo de dependencias: tema44.md

  - Proyecto Integrador y Despliegue:
    - Desarrollo del proyecto integrador: tema51.md
    - Despliegue en nube: tema52.md

theme:
  name: readthedocs

